development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mysql_lock_wait_timeout_problem_development
  pool: 10
  username: root
  password:
  socket: /tmp/mysql.sock
  local_infile: true

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mysql_lock_wait_timeout_problem_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
